WITH GROUPS AS (
    SELECT
        CITY,
        TO_TIMESTAMP_NTZ(CREATED / 1000)::TIMESTAMP_NTZ(3) AS CREATED,
        DESCRIPTION,
        NAME AS GROUP_NAME,
        CAST(LAT AS FLOAT) AS LATITUDE,
        CAST(LON AS FLOAT) AS LONGITUDE,
        LINK,
        GROUP_ID,
        TOPIC.VALUE::VARCHAR AS TOPIC
    FROM
        MEETUP.RAW.RAW_GROUPS,
        LATERAL FLATTEN(INPUT => TOPICS) AS TOPIC
)

SELECT * FROM GROUPS