version: 2

models:
  - name: dim_groups
    description: Cleansed table which contains Meet Up groups.
    columns:
      - name: group_id
        description: Unique identifier for this group. This is used as a reference in other objects.
        tests: 
          - unique
          - not_null
          - relationships: 
              to: ref('dim_topics')
              field: group_id
      - name: group_city
        description: Name of the city where the group resides.
      - name: group_date_created
        description: Timestamp of when the group was created.
      - name: description
        description: Description of the group.
      - name: description_without_tags
        description: Description of the group without HTML tags.
      - name: group_name
        description: Name of the group. 
      - name: group_latitude
        description: Latitude of the place where the group resides.
      - name: group_longitude
        description: Longitude of the place where the group resides.
      - name: link
        description: Link to the group's homepage.


  - name: dim_topics
    description: Cleansed table which contains Meet Up topics.
    columns:
      - name: topic_id
        description: Unique identifier for this topic.
        tests: 
          - unique
          - not_null
      - name: group_id
        description: Unique identifier for this group.
      - name: topic
        description: Topics that this a group discusses or otherwise associates with.
          

  - name: dim_users
    description: Cleansed table which contains Meet Up users.
    columns:
      - name: user_id
        description: A unique identifier for this user.
        tests: 
          - unique
          - not_null
      - name: user_city
        description: City where the user resides.
      - name: user_country
        description: Country where the user resides.
      - name: user_hometown
        description: Town that the user specified as their home town.



  - name: dim_venues
    description: Cleansed table which contains Meet Up venues.
    columns:
      - name: venue_id
        description: A unique identifier for this venue.
        tests: 
          - unique
          - not_null
      - name: venue_name
        description: The name of the venue.
      - name: venue_city
        description: The city where the venue is located.
      - name: venue_country
        description: The country where the venue is located.
      - name: venue_latitude
        description: The lattitude of the venue location.
      - name: venue_longitude
        description: The longitude of the vanue location.



  - name: dim_events
    description: Cleansed table which contains Meet Up events.
    columns:
      - name: event_id
        description: A unique identifier for this event.
        tests: 
          - unique
          - not_null
      - name: event_name
        description: The name of the event.
      - name: event_description
        description: The description of the event.
      - name: event_description_without_tags
        description: The description of the event without HTML tags.



  - name: fact_rsvps
    description: Cleansed table which contains Meet Up RSVPS objects.
    columns:
      - name: group_id
        description: The unique identifier of the group that organised this event.
        tests: 
          - relationships: 
              to: ref('dim_groups')
              field: group_id
      - name: venue_id
        description: Unique identifier of the venue where this event takes place (see below).
        tests: 
          - relationships: 
              to: ref('dim_venues')
              field: venue_id
      - name: event_id
        description: Unique identifier of the event.
        tests: 
          - relationships: 
              to: ref('dim_events')
              field: event_id
      - name: user_id
        description: The unique identifier of the user that RSVPed for this event.
        tests: 
          - relationships: 
              to: ref('dim_users')
              field: user_id
      - name: rsvp_response
        description: Yes or No, the indication of whether this user will attend the event.
        tests: 
          - accepted_values: 
              values: ['yes','no','waitlist']
      - name: rsvp_when
        description: Timestamp of the moment the user gave their RSVP.
      - name: rsvp_guest
        description: If permitted, the number of guests that the user is planning to bring to the event.
      - name: is_latest_rsvp_when
        description: Boolean column indicating if the RSVP when is the last one.
